title: Actual Point
author: Ing. Diego Vicente et al
email: vicentel@ing.unlpam.edu.ar
description: > # this means to ignore newlines until "baseurl:"
  Sistema de monitoreo inteligente con transmisión inalámbrica de 
  energía y datos: sin cables ni baterías
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
